### ISSUE TITLE
Gorm 1.4.0 crash clicking on any image

### ISSUE THREAD

**Issue by buzzdeee** [gnustep/apps-gorm#49]
Starting Gorm, -> Document -> New Module -> New Empty

Then clicking on the "Images" icon to open up all images, Gorm crashes, once clicking on any of the images:

```
(gdb) r
Starting program: /usr/local/bin/Gorm 

Program received signal SIGSEGV, Segmentation fault.
0x00000b520f4c0f17 in -[GormResourceEditor mouseDown:] (self=0xb5232aa6308, _cmd=0xb52c31b65f8 <.objc_selector_mouseDown:_v240:816>, theEvent=0xb52a4d24408) at GormResourceEditor.m:244
244           if ([cells[row][column] isEnabled])
(gdb) bt
#0  0x00000b520f4c0f17 in -[GormResourceEditor mouseDown:] (self=0xb5232aa6308, _cmd=0xb52c31b65f8 <.objc_selector_mouseDown:_v240:816>, theEvent=0xb52a4d24408) at GormResourceEditor.m:244
#1  0x00000b52c3057204 in -[NSWindow sendEvent:] (self=0xb52d309e408, _cmd=0xb52c31b6a28 <.objc_selector_sendEvent:_v240:816>, theEvent=0xb52a4d24408) at NSWindow.m:4158
#2  0x00000b52c2e1465e in -[NSApplication sendEvent:] (self=0xb52243e01c8, _cmd=0xb52c31b6a28 <.objc_selector_sendEvent:_v240:816>, theEvent=0xb52a4d24408) at NSApplication.m:2151
#3  0x00000b52c2e12d10 in -[NSApplication run] (self=0xb52243e01c8, _cmd=0xb52c31b4668 <objc_selector_run_v160:8>) at NSApplication.m:1588
#4  0x00000b52c2ded10e in NSApplicationMain (argc=1, argv=0x770d9a1f0d38) at Functions.m:119
#5  0x00000b4fd3489c4c in gnustep_base_user_main (argc=1, argv=0x770d9a1f0d38) at main.m:30
#6  0x00000b52444701ab in main (argc=1, argv=0x770d9a1f0d38, env=0x770d9a1f0d48) at NSProcessInfo.m:1018
#7  0x00000b4fd348660b in _start ()
(gdb) frame 0
#0  0x00000b520f4c0f17 in -[GormResourceEditor mouseDown:] (self=0xb5232aa6308, _cmd=0xb52c31b65f8 <.objc_selector_mouseDown:_v240:816>, theEvent=0xb52a4d24408) at GormResourceEditor.m:244
244           if ([cells[row][column] isEnabled])
(gdb) print cells
$2 = (id **) 0x0
(gdb) print row
$3 = 0
(gdb) print column
$4 = 1
(gdb)
```

**Comment by gcasa** [comment]
Applied the page on the main version, please test.
